[versions]
agp = "8.11.1"
kotlin = "2.0.21"
coreKtx = "1.10.1"
junit = "4.13.2"
junitVersion = "1.1.5"
espressoCore = "3.5.1"
lifecycleRuntimeKtx = "2.6.1"

okhttp = "4.12.0"
kotlinx-coroutines = "1.7.3"
appcompat = "1.7.1"

media3 = "1.3.1"
androidx-browser = "1.8.0" # Use the latest stable version
gson = "2.10.1"
room = "2.6.1"

hilt = "2.51"
hilt-compiler = "2.51"
hilt-navigation = "1.1.0"

androidx-security = "1.0.0"
recyclerview = "1.4.0"
pagingCommonAndroid = "3.3.6"
pagingRuntimeKtx = "3.3.6"
material = "1.13.0"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }

okhttp = { group = "com.squareup.okhttp3", name = "okhttp", version.ref = "okhttp" }
kotlinx-coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "kotlinx-coroutines" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
androidx-media3-session = { group = "androidx.media3", name = "media3-session", version.ref = "media3" }
androidx-media3-common = { group = "androidx.media3", name = "media3-common", version.ref = "media3" }
androidx-browser = { group = "androidx.browser", name = "browser", version.ref = "androidx-browser" }
google-gson = { module = "com.google.code.gson:gson", version.ref = "gson" }

androidx-room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
androidx-room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "room" } # Coroutine support for Room
androidx-room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" } # Annotation Processor
androidx-room-paging = { group = "androidx.room", name = "room-paging", version.ref = "room" } # paging

hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "hilt-compiler" }
hilt-navigation = { module = "androidx.hilt:hilt-navigation-fragment", version.ref = "hilt-navigation" }

security-crypto = { group = "androidx.security", name = "security-crypto", version.ref = "androidx-security" }
androidx-recyclerview = { group = "androidx.recyclerview", name = "recyclerview", version.ref = "recyclerview" }
androidx-paging-common-android = { group = "androidx.paging", name = "paging-common-android", version.ref = "pagingCommonAndroid" }
androidx-paging-runtime-ktx = { group = "androidx.paging", name = "paging-runtime-ktx", version.ref = "pagingRuntimeKtx" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }


